name: Deploy web app to GithubPages
on:
  push:
    branches: [ "main" ]

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x" # Use the same target version as your Blazor project

      # Step 3: Publish the Blazor WebAssembly app
      - name: Publish Blazor WebAssembly app
        run: dotnet publish -c Release -o build_outputs_folder

      # Step 4: Upload static files as an artifact (for Pages deployment)
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build_outputs_folder/wwwroot    # Blazor WebAssembly outputs are inside "wwwroot"
  
  # Deploy job
  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
